### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by GeoTuxMan** [gher-ulg/divand.py#1]
Hi,

I followed all steps to install divand.py (on a workstation with Win 8.1 64 bit)
After I downloaded divand.py, I set a system variable:
PYTHONPATH=C:\Python27\;C:\Python27\Lib;C:\Python27\DLLs;C:\divand.py\divand\divand.py

I run:  python divand_argo.py
  I got : ImportError: No module named divand

Cheers!
George

**Comment by Alexander-Barth** [comment]
Hi George,

The repo (divand.py) is a in fact more an internal repo for the GHER to build a web-application for making DIVA analyses. We plan to deploy this on a Linux server, so the only OS that we plan to support is Linux. The package divand.py is not indent for users who want to run DIVAnd. For this case, they can use the julia interface directly (which we support on Windows).  

The Import error however, is probably related to the fact that you include the file and not a directory in the `PYTHONPATH`. I guess that using `PYTHONPATH=C:\Python27;C:\Python27\Lib;C:\Python27\DLLs;C:\divand.py\divand\` will make python find the module `divand`. But beside this, it is unlikely that divand.py will work on Windows.

I will mention this in the file README.md. 

Cheers,
Alex
